In [1]:
# Dependencies
import requests
import json
import pandas as pd

from config import gkey

In [2]:
df = pd.read_csv("dc_crime_data_2019.csv")
df

,X,Y,CCN,REPORT_DAT_YR,REPORT_DAT_MONTH,REPORT_DAT_DAY,REPORT_DAT_TIME,REPORT_DAT_FORMAT,REPORT_DAT_WEEKDAY,SHIFT,...,BLOCK_GROUP,CENSUS_TRACT,VOTING_PRECINCT,LATITUDE,LONGITUDE,BID,START_DATE,END_DATE,OBJECTID,OCTO_RECORD_ID
0,-77.029635,38.911496,19138665,2019,8,7,03:58:04.000Z,7/8/2019,Monday,MIDNIGHT,...,005001 2,5001.0,Precinct 16,38.911488,-77.029632,NaN,2019-08-06T20:00:48.000Z,2019-08-06T22:30:15.000Z,356044774,19138665-01
1,-77.030790,38.918117,19138667,2019,8,7,00:23:17.000Z,7/8/2019,Monday,MIDNIGHT,...,004400 1,4400.0,Precinct 22,38.918109,-77.030788,NaN,2019-08-06T22:45:46.000Z,2019-08-07T00:11:08.000Z,356044775,19138667-01
2,-77.030790,38.918117,19138668,2019,8,7,00:21:21.000Z,7/8/2019,Monday,MIDNIGHT,...,004400 1,4400.0,Precinct 22,38.918109,-77.030788,NaN,2019-08-06T23:17:30.000Z,2019-08-07T00:11:12.000Z,356044776,19138668-01
3,-77.040081,38.911133,19138669,2019,8,7,00:05:15.000Z,7/8/2019,Monday,MIDNIGHT,...,005301 2,5301.0,Precinct 15,38.911125,-77.040078,NaN,2019-08-06T22:49:45.000Z,2019-08-06T23:49:50.000Z,356044777,19138669-01
4,-77.051638,38.900913,19138682,2019,8,7,00:06:15.000Z,7/8/2019,Monday,MIDNIGHT,...,005600 4,5600.0,Precinct 3,38.900905,-77.051635,NaN,2019-08-06T23:45:17.000Z,2019-08-06T23:50:26.000Z,356044778,19138682-01
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
27014,-77.015187,38.911868,19068953,2019,4,23,15:50:26.000Z,23/4/2019,23/4/2019,EVENING,...,004600 2,4600.0,Precinct 19,38.911860,-77.015185,NaN,2019-04-23T14:30:09.000Z,2019-04-23T15:00:31.000Z,356440440,19068953-01
27015,-76.988163,38.831468,19068962,2019,4,23,17:03:28.000Z,23/4/2019,23/4/2019,EVENING,...,009700 1,9700.0,Precinct 121,38.831461,-76.988160,NaN,2019-04-23T15:16:31.000Z,2019-04-23T15:26:43.000Z,356440441,19068962-01
27016,-77.032733,38.929521,19068966,2019,4,23,22:34:46.000Z,23/4/2019,23/4/2019,EVENING,...,003000 1,3000.0,Precinct 39,38.929513,-77.032731,NaN,2019-04-23T13:07:09.000Z,2019-04-23T13:12:41.000Z,356440442,19068966-01
27017,-76.964790,38.934538,19068975,2019,4,23,23:25:45.000Z,23/4/2019,23/4/2019,MIDNIGHT,...,011100 2,11100.0,Precinct 69,38.934530,-76.964787,NaN,2019-04-23T14:31:20.000Z,2019-04-23T15:59:37.000Z,356440443,19068975-01
27018,-76.998148,38.825614,19068992,2019,4,23,19:22:36.000Z,23/4/2019,23/4/2019,EVENING,...,009811 2,9811.0,Precinct 125,38.825606,-76.998146,NaN,2019-04-23T14:51:05.000Z,2019-04-23T17:42:43.000Z,356440444,19068992-01

In [3]:
lat_lon_df = df[["LATITUDE", "LONGITUDE"]]
lat_lon_df

        LATITUDE  LONGITUDE
0      38.911488 -77.029632
1      38.918109 -77.030788
2      38.918109 -77.030788
3      38.911125 -77.040078
4      38.900905 -77.051635
...          ...        ...
27014  38.911860 -77.015185
27015  38.831461 -76.988160
27016  38.929513 -77.032731
27017  38.934530 -76.964787
27018  38.825606 -76.998146

[27019 rows x 2 columns]

In [23]:
# Make request for zip code from google API
zipcodes = []
for lat, lon in zip(lat_lon_df["LATITUDE"], lat_lon_df["LONGITUDE"]):
    target_url = f"https://maps.googleapis.com/maps/api/geocode/json?latlng={lat},{lon}&key={gkey}"
    geo_data = requests.get(target_url).json()
    zipcode = geo_data["results"][0]["address_components"][6]["long_name"]
    print(zipcode)
    zipcodes.append(zipcode)
print(zipcodes)

20009
20009
20009
20009
20037

IndexError: list index out of range